name: Weekly PDF Monitor

on:
  schedule:
    # Runs every Monday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Important: This allows the workflow to commit changes back
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run PDF monitor
      env:
        PDF_URL: ${{ secrets.PDF_URL }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python monitor.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add previous_content.txt
        git diff --staged --quiet || git commit -m "Update previous content for next comparison [automated]"
        git push
